/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.*;
/**
 *
 * @author L'empereur Redho
 */
public class mainWindows extends javax.swing.JFrame {

    /**
     * Creates new form mainWindows
     */
    public mainWindows() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        switchType = new javax.swing.ButtonGroup();
        switchMethod = new javax.swing.ButtonGroup();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        bg = new javax.swing.JPanel();
        leftPanel = new javax.swing.JPanel();
        label = new javax.swing.JLabel();
        aesSelect = new javax.swing.JRadioButton();
        desSelect = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        mainPanel = new javax.swing.JPanel();
        encryptPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        plainText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        encryptKeyText = new javax.swing.JTextField();
        encryptButton = new javax.swing.JButton();
        encryptedText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        decryptPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        cipherText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        decryptKeyText = new javax.swing.JTextField();
        decryptButton = new javax.swing.JButton();
        resultText = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        rbtEncryptSelect = new javax.swing.JRadioButton();
        rbtDecryptSelect = new javax.swing.JRadioButton();

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Key");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        setMaximumSize(bg.getMaximumSize());
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(600, 400));

        bg.setBackground(new java.awt.Color(51, 51, 51));

        leftPanel.setBackground(new java.awt.Color(102, 102, 102));

        label.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        label.setForeground(new java.awt.Color(255, 255, 255));
        label.setText("Choose Method");

        aesSelect.setBackground(new java.awt.Color(102, 102, 102));
        switchMethod.add(aesSelect);
        aesSelect.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        aesSelect.setForeground(new java.awt.Color(255, 255, 255));
        aesSelect.setSelected(true);
        aesSelect.setText("AES - 256");
        aesSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aesSelectActionPerformed(evt);
            }
        });

        desSelect.setBackground(new java.awt.Color(102, 102, 102));
        switchMethod.add(desSelect);
        desSelect.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        desSelect.setForeground(new java.awt.Color(255, 255, 255));
        desSelect.setText("Triple DES");
        desSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desSelectActionPerformed(evt);
            }
        });

        jRadioButton3.setBackground(new java.awt.Color(102, 102, 102));
        switchMethod.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("jRadioButton1");

        jRadioButton4.setBackground(new java.awt.Color(102, 102, 102));
        switchMethod.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton4.setText("jRadioButton1");

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aesSelect)
                    .addComponent(desSelect)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4)
                    .addComponent(label))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        leftPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {aesSelect, desSelect, jRadioButton3, jRadioButton4});

        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label)
                .addGap(18, 18, 18)
                .addComponent(aesSelect)
                .addGap(18, 18, 18)
                .addComponent(desSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        leftPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {aesSelect, desSelect, jRadioButton3, jRadioButton4});

        mainPanel.setBackground(new java.awt.Color(51, 51, 51));
        mainPanel.setLayout(new java.awt.CardLayout());

        encryptPanel.setBackground(new java.awt.Color(51, 51, 51));

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Plain Text");

        plainText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        plainText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plainTextActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Key");

        encryptKeyText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        encryptButton.setBackground(new java.awt.Color(0, 0, 0));
        encryptButton.setForeground(new java.awt.Color(255, 255, 255));
        encryptButton.setText("Encrypt!");

        encryptedText.setEditable(false);
        encryptedText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        encryptedText.setText("-- Sample --");
        encryptedText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encryptedTextActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cipher Text");

        javax.swing.GroupLayout encryptPanelLayout = new javax.swing.GroupLayout(encryptPanel);
        encryptPanel.setLayout(encryptPanelLayout);
        encryptPanelLayout.setHorizontalGroup(
            encryptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(encryptPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(encryptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(encryptedText, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(plainText, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(encryptKeyText, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1)
                    .addGroup(encryptPanelLayout.createSequentialGroup()
                        .addGroup(encryptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(encryptButton)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(0, 92, Short.MAX_VALUE)))
                .addContainerGap())
        );
        encryptPanelLayout.setVerticalGroup(
            encryptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, encryptPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(plainText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(encryptKeyText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(encryptButton)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(encryptedText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(encryptPanel, "encryptPanel");

        decryptPanel.setBackground(new java.awt.Color(51, 51, 51));

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Encrypted Text");

        cipherText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cipherText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cipherTextActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Key");

        decryptKeyText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        decryptButton.setBackground(new java.awt.Color(0, 0, 0));
        decryptButton.setForeground(new java.awt.Color(255, 255, 255));
        decryptButton.setText("Decrypt!");

        resultText.setEditable(false);
        resultText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        resultText.setText("-- Sample --");
        resultText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultTextActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Plain Text");

        javax.swing.GroupLayout decryptPanelLayout = new javax.swing.GroupLayout(decryptPanel);
        decryptPanel.setLayout(decryptPanelLayout);
        decryptPanelLayout.setHorizontalGroup(
            decryptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(decryptPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(decryptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resultText, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cipherText, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(decryptKeyText, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2)
                    .addGroup(decryptPanelLayout.createSequentialGroup()
                        .addGroup(decryptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(decryptButton)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(0, 66, Short.MAX_VALUE)))
                .addContainerGap())
        );
        decryptPanelLayout.setVerticalGroup(
            decryptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, decryptPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cipherText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(decryptKeyText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(decryptButton)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(decryptPanel, "decryptPanel");

        switchType.add(rbtEncryptSelect);
        rbtEncryptSelect.setForeground(new java.awt.Color(255, 255, 255));
        rbtEncryptSelect.setSelected(true);
        rbtEncryptSelect.setText("Encrypt");
        rbtEncryptSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtEncryptSelectActionPerformed(evt);
            }
        });

        switchType.add(rbtDecryptSelect);
        rbtDecryptSelect.setForeground(new java.awt.Color(255, 255, 255));
        rbtDecryptSelect.setText("Decrypt");
        rbtDecryptSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtDecryptSelectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(rbtEncryptSelect)
                        .addGap(18, 18, 18)
                        .addComponent(rbtDecryptSelect)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE))
                .addContainerGap())
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtEncryptSelect)
                    .addComponent(rbtDecryptSelect))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(bg, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void desSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desSelectActionPerformed

    private void aesSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aesSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aesSelectActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void rbtDecryptSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtDecryptSelectActionPerformed
        CardLayout main = (CardLayout)mainPanel.getLayout();
        main.show(mainPanel, "decryptPanel");
    }//GEN-LAST:event_rbtDecryptSelectActionPerformed

    private void rbtEncryptSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtEncryptSelectActionPerformed
        CardLayout main = (CardLayout)mainPanel.getLayout();
        main.show(mainPanel, "encryptPanel");
    }//GEN-LAST:event_rbtEncryptSelectActionPerformed

    private void resultTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultTextActionPerformed

    private void cipherTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cipherTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cipherTextActionPerformed

    private void encryptedTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encryptedTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_encryptedTextActionPerformed

    private void plainTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plainTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plainTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainWindows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainWindows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainWindows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainWindows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainWindows().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton aesSelect;
    private javax.swing.JPanel bg;
    private javax.swing.JTextField cipherText;
    private javax.swing.JButton decryptButton;
    private javax.swing.JTextField decryptKeyText;
    private javax.swing.JPanel decryptPanel;
    private javax.swing.JRadioButton desSelect;
    private javax.swing.JButton encryptButton;
    private javax.swing.JTextField encryptKeyText;
    private javax.swing.JPanel encryptPanel;
    private javax.swing.JTextField encryptedText;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel label;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField plainText;
    private javax.swing.JRadioButton rbtDecryptSelect;
    private javax.swing.JRadioButton rbtEncryptSelect;
    private javax.swing.JTextField resultText;
    private javax.swing.ButtonGroup switchMethod;
    private javax.swing.ButtonGroup switchType;
    // End of variables declaration//GEN-END:variables
}
